import path from 'path';
import fs from 'fs-extra';
import { logger, printBanner, printSection } from '../utils/logger';

const META_FILE = '.sprygen/meta.json';

export async function migrateInitCommand(): Promise<void> {
  printBanner();
  printSection('Migrate Init — Converting project to Flyway');

  const projectDir = process.cwd();
  const pomPath    = path.join(projectDir, 'pom.xml');
  const gradlePath = path.join(projectDir, 'build.gradle');
  const ymlPath    = path.join(projectDir, 'src/main/resources/application.yml');
  const migrationDir = path.join(projectDir, 'src/main/resources/db/migration');

  // Verify we are inside a Java project
  if (!(await fs.pathExists(pomPath)) && !(await fs.pathExists(gradlePath))) {
    logger.error('No pom.xml or build.gradle found. Run this command inside a Spring Boot project root.');
    process.exit(1);
  }

  // Create migration directory
  await fs.ensureDir(migrationDir);
  logger.info('Created: src/main/resources/db/migration/');

  // Generate V1 baseline SQL
  const initSql = `-- ============================================================
--  V1 — Baseline schema (auto-generated by Sprygen migrate:init)
--  Generated: ${new Date().toISOString().split('T')[0]}
-- ============================================================

-- TODO: Add your existing table CREATE statements here.
-- This file is intentionally blank — fill it with your current schema
-- so Flyway can track future changes from this baseline.

-- Example:
-- CREATE TABLE IF NOT EXISTS users (
--     id       BIGINT AUTO_INCREMENT PRIMARY KEY,
--     email    VARCHAR(255) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL
-- );
`;
  const initSqlPath = path.join(migrationDir, 'V1__baseline.sql');
  if (await fs.pathExists(initSqlPath)) {
    logger.warn('V1__baseline.sql already exists — skipping to avoid overwriting.');
  } else {
    await fs.writeFile(initSqlPath, initSql, 'utf8');
    logger.info('Created: src/main/resources/db/migration/V1__baseline.sql');
  }

  // Patch application.yml to add Flyway config and set ddl-auto: none
  if (await fs.pathExists(ymlPath)) {
    let yml = await fs.readFile(ymlPath, 'utf8');

    // Replace ddl-auto
    if (yml.includes('ddl-auto:')) {
      yml = yml.replace(/ddl-auto:\s*.+/g, 'ddl-auto: none');
      logger.info('Updated application.yml: ddl-auto → none');
    }

    // Add Flyway block if not already present
    if (!yml.includes('flyway:')) {
      yml += `\n  flyway:\n    enabled: true\n    locations: classpath:db/migration\n    baseline-on-migrate: true\n`;
      logger.info('Updated application.yml: added Flyway configuration block');
    }

    await fs.writeFile(ymlPath, yml, 'utf8');
  } else {
    logger.warn('application.yml not found — could not patch Flyway settings automatically.');
  }

  // Add Flyway dependency to pom.xml
  if (await fs.pathExists(pomPath)) {
    let pom = await fs.readFile(pomPath, 'utf8');
    if (!pom.includes('flyway-core')) {
      const flywayDep = `
        <!-- Flyway Database Migrations -->
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
        </dependency>`;
      pom = pom.replace('</dependencies>', `${flywayDep}\n    </dependencies>`);
      await fs.writeFile(pomPath, pom, 'utf8');
      logger.info('Updated pom.xml: added Flyway dependencies');
    }
  }

  // Write .sprygen/meta.json so future add-entity knows to generate migrations
  const metaPath = path.join(projectDir, META_FILE);
  await fs.ensureDir(path.dirname(metaPath));
  const meta: Record<string, unknown> = {};
  if (await fs.pathExists(metaPath)) {
    Object.assign(meta, await fs.readJson(metaPath));
  }
  meta.migrationVersion = 1;
  meta.flyway = true;
  await fs.writeJson(metaPath, meta, { spaces: 2 });
  logger.info('Created: .sprygen/meta.json (migration version tracker)');

  console.log();
  logger.success('Project successfully converted to Flyway migrations!');
  console.log();
  logger.info('  Next steps:');
  logger.info('  1. Fill in V1__baseline.sql with your existing schema');
  logger.info('  2. Run your app — Flyway will apply the baseline on first boot');
  logger.info('  3. Use sprygen add-entity to generate future migrations automatically');
}
